### ISSUE TITLE
Testing on custom data + some clarification on method

### ISSUE THREAD

**Issue by deeptibhegde** [leolyj/DCA_SRSFE#6]
Is the data pre-processing for scene flow required if we only wish to perform inference? I do not understand why "generated data" is required for the network to perform inference, since it includes ground truth scene flow (from my understanding). Is it possible to estimate flow from just a sequence of lidar scenes?

**Comment by JZ-9962** [comment]
Hi! 
You can skip the flow computing process during inference. The flow included in the "generated data" is only used as scene flow label for loss calculation. So feel free to modify the code at inference stage.
